### PR TITLE
LX-52: Update go mod, update simMiner

### PR DESCRIPTION
**Pull request by PaulSnow**
Update the simMiner and fix the go.mod and go.sum files.

Note that this does not change any code that executes at run time.  Does clean up some output and timing when using simMiner for testing.

### CODE REVIEW

**Comment by WhoSoup** [comment]
any chance we can get go-humanize out of the go.mod file, too? put it in a separate mod file for the simMiner only, that way we'll have a no-import lxrhash package

**Comment by Emyrk** [comment]
> any chance we can get go-humanize out of the go.mod file, too? put it in a separate mod file for the simMiner only, that way we'll have a no-import lxrhash package

Does that work to nest go.mod files like that? Or just an entirely new go.mod

**Comment by WhoSoup** [comment]
> > any chance we can get go-humanize out of the go.mod file, too? put it in a separate mod file for the simMiner only, that way we'll have a no-import lxrhash package
> 
> Does that work to nest go.mod files like that? Or just an entirely new go.mod

i think you can nest go mod files

**Comment by Emyrk** [comment]
@WhoSoup I haven't found anything solid about nesting go mod files. Can we push handling the dependency until later? It's pretty minor atm, and we either need to make a `Tools` repo, or find a way to have dev dependecies/split the go mod files.

**Comment by PaulSnow** [comment]
We will close this at this time.  Does not interesting push the ball forward.

**Pull request closed without merging**
